[phases.setup]
nixPkgs = ['nodejs-18_x', 'openssl', 'pkg-config']
aptPkgs = ['ca-certificates']

[phases.install]
cmds = [
  'npm config set legacy-peer-deps true',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false' 